/*
    This file was generated automatically by Alchitry Labs 2.0.50-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module regfile_memory (
        input wire clk,
        input wire rst,
        input wire [4:0] ra1,
        input wire [4:0] ra2,
        output reg [31:0] rd1,
        output reg [31:0] rd2,
        input wire [4:0] wa,
        input wire [31:0] wd,
        input wire we
    );
    logic [31:0][31:0] D_registers_d, D_registers_q = {32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0};
    always @* begin
        D_registers_d = D_registers_q;
        
        D_registers_d = D_registers_q;
        rd1 = 1'h0;
        rd2 = 1'h0;
        rd1 = D_registers_q[ra1];
        rd2 = D_registers_q[ra2];
        if (we & ~(&wa)) begin
            D_registers_d[wa] = wd;
        end
    end
    
    
    always @(posedge (clk)) begin
        if ((rst) == 1'b1) begin
            D_registers_q <= {32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0, 32'h0};
        end else begin
            D_registers_q <= D_registers_d;
        end
    end
endmodule